### ISSUE TITLE
Button ordering in 2.0.1: "Versioning..." in between "Save" and "Publish"

### ISSUE THREAD

**Issue by JorisDebonnet** [heyday/silverstripe-versioneddataobjects#38] opened 2016-10-15 22:16 UTC
The 2.0.1 release has placed the "Versioning..." button in between the buttons "Save" and "Publish". Is this an intentional change? It makes it less consistent with the versioning buttons on SiteTree items... In my opinion it would be the most intuitive if it was as close to that as possible :)

**Comment by JorisDebonnet** [comment] 2016-10-15 22:20
I am also using `dnadesign/silverstripe-elemental` and `bluehousegroup/silverstripe-data-object-version-viewer`, which I suppose is relevant. Should I go complain at the latter instead? :)

![buttons](https://cloud.githubusercontent.com/assets/3286264/19413723/148ab770-9336-11e6-80f5-7ba5a73da298.png)

**Comment by jebates** [comment] 2016-10-17 22:26
Hi, thanks for the message.

No need to go to the developers of those two modules, as I am experiencing this in a project that does not have them installed.

The "Versioning..." button (this comes from Uncle Cheese's Better Buttons module) is between the "Save" and "Publish" buttons from version 2.0.1 onwards - this was due to the merged pull request at https://github.com/heyday/silverstripe-versioneddataobjects/pull/33 where an incompatibility between Better Buttons and Versioned Data Objects was fixed (Better Buttons was overwriting all the buttons).

Anyway, the cause of the ordering issue is because the default publish button was being removed and this leaves the "Versioning..." button to move to the second position in the array of actions. And then the new publish button action is added to the end of the array. This is done using the push method on the FieldList class.

The fix was to use the insertBefore method instead of the push method. Release 2.0.3 contains the fix.

Cheers.

**Closed by jebates** 2016-10-17 22:26 UTC
